export const categoryEmojis: Record<string, string> = {
  length: '📏',
  mass: '⚖️',
  time: '⏱️',
  temperature: '🌡️',
  amountOfSubstance: '🧪',
  electricCurrent: '⚡',
  luminousIntensity: '💡',
  planeAngle: '📐',
  solidAngle: '🔭',
  area: '⬜',
  volume: '🧊',
  speed: '🚀',
  acceleration: '📈',
  force: '💪',
  pressure: '🔩',
  energy: '🔋',
  power: '⚙️',
  torque: '🔧',
  frequency: '📻',
  density: '🪨',
  dynamicViscosity: '🍯',
  kinematicViscosity: '💧',
  volumetricFlow: '🚿',
  massFlow: '🌊',
  linearMomentum: '➡️',
  angularVelocity: '🔄',
  angularAcceleration: '🌀',
  surfaceTension: '💦',
  electricCharge: '🔌',
  voltage: '🔶',
  resistance: '🛑',
  conductance: '📶',
  capacitance: '🗲',
  inductance: '🧲',
  magneticField: '🧭',
  magneticFlux: '🌐',
  illuminance: '☀️',
  luminance: '🌟',
  luminousFlux: '✨',
  specificHeat: '🔥',
  thermalConductivity: '♨️',
  specificEntropy: '📊',
  absorbedDose: '☢️',
  equivalentDose: '⚠️',
  radioactivity: '🎇',
  digitalStorage: '💾',
  dataTransfer: '📡',
  fuelConsumption: '⛽',
  culinary: '🍳',
};

export function getCategoryEmoji(categoryId: string): string {
  return categoryEmojis[categoryId] ?? '📋';
}
